opt/vyatta/etc/modprobe.d etc
opt/vyatta/sbin
opt/vyatta/share/vyatta-cfg/templates/interfaces/bonding
opt/vyatta/share/vyatta-cfg/templates/interfaces/bridge
opt/vyatta/share/vyatta-cfg/templates/interfaces/ethernet
opt/vyatta/share/vyatta-cfg/templates/interfaces/openvpn
opt/vyatta/share/vyatta-cfg/templates/interfaces/pseudo-ethernet
opt/vyatta/share/vyatta-cfg/templates/interfaces/tunnel
opt/vyatta/share/vyatta-cfg/templates/interfaces/wireless
opt/vyatta/share/vyatta-cfg/templates/interfaces/wirelessmodem
opt/vyatta/share/vyatta-cfg/templates/interfaces/l2tpv3
opt/vyatta/share/vyatta-cfg/templates/interfaces/vxlan

