etc/modprobe.d
opt/vyatta/sbin
opt/vyatta/share/vyatta-cfg/templates/interfaces/bridge
opt/vyatta/share/vyatta-cfg/templates/interfaces/loopback
opt/vyatta/share/vyatta-cfg/templates/interfaces/openvpn
opt/vyatta/share/vyatta-cfg/templates/interfaces/tunnel
opt/vyatta/share/vyatta-cfg/templates/interfaces/ethernet/node.tag/ipv6
opt/vyatta/share/vyatta-cfg/templates/interfaces/ethernet/node.tag/vif/node.tag/ipv6
